* pytest-pdb-break
See the main source file's front matter for additional options and info.

** Installation
No MELPA yet, but straight.el users can use this:
   #+BEGIN_SRC emacs-lisp
     '(:host github :repo "poppyschmo/pytest-pdb-break"
             :files (:defaults "emacs/*.el" (:exclude "emacs/*-test.el")))

   #+END_SRC

** Usage
With point in the body of some test, run =M-x pytest-pdb-break-here=.

That's the one and only command, so far. By default, =C-u= will trigger a prompt for pytest
options, which are then included in subsequent runs until cleared. Clearing is done by
killing the input line or calling the command with =C-u 0=. Prompt history and file-path
completion should work as expected, but pytest option names have yet to be added.

Persistent options can be stored in =pytest-pdb-break-extra-opts=. These are inserted before
per-session options in the command line.

The namesake minor mode is useful for setup/teardown of standard PDB-related tasks, like
=realgud= tracking, etc. It runs on activation inside the newly created
=inferior-python-mode= buffer and once again when that buffer is killed.
